import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * THE BUG THIS EXISTS FOR — a migration that was skipped while the migrator reported success.
 *
 * Drizzle's migrator does not track WHICH migrations ran. It stores a single watermark: the
 * `when` (epoch millis) of the last migration it applied. On each boot it applies every journal
 * entry whose `when` is GREATER than that watermark, and skips the rest.
 *
 * So `when` is not documentation. It is the ordering key, and it must be monotonic.
 *
 * What happened: migration 0009 was hand-written, and its journal entry was given an invented
 * `when` about 1.2 hours in the FUTURE. It applied, setting the watermark to a future timestamp.
 * The next migration, 0010, was generated by drizzle-kit with the real current time — which was
 * LOWER — so the migrator skipped it entirely and logged `migrations_applied` anyway. `audit_events`
 * was never created, the `call_learnings` foreign key was never added, and nothing failed. It
 * would have "fixed itself" once wall-clock time caught up, which is worse: the symptom
 * disappears while the cause stays.
 *
 * Two invariants, both cheap:
 *   1. `when` strictly increases with `idx`
 *   2. no `when` is in the future
 *
 * The second is the one that actually catches the mistake, because a single future timestamp looks
 * perfectly monotonic until the next migration is generated.
 */

const MIGRATIONS = fileURLToPath(new URL('./migrations', import.meta.url));

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
}

function journal(): { entries: JournalEntry[] } {
  return JSON.parse(readFileSync(join(MIGRATIONS, 'meta', '_journal.json'), 'utf8'));
}

/**
 * 0000–0002 were hand-written early and carry invented timestamps that are out of order with each
 * other (0001 is dated a YEAR before 0000). They were applied long ago — before this repo had a
 * runtime migrator at all — and the stored watermark is far past them, so the disorder is inert
 * history rather than a live problem. Rewriting their timestamps now would not change anything
 * already applied and would only risk re-running them somewhere.
 *
 * Grandfathered explicitly, so the invariant still binds every migration from 0003 on. This
 * constant should never grow.
 */
const GRANDFATHERED_THROUGH_IDX = 2;

describe('migration journal', () => {
  it('has strictly increasing `when` timestamps', () => {
    const entries = journal().entries;
    const outOfOrder: string[] = [];

    for (let i = Math.max(1, GRANDFATHERED_THROUGH_IDX + 1); i < entries.length; i++) {
      const prev = entries[i - 1];
      const cur = entries[i];
      if (cur.when <= prev.when) {
        outOfOrder.push(
          `${cur.tag} (when=${cur.when}) is not after ${prev.tag} (when=${prev.when}) — ` +
            'it will be SKIPPED, silently, and the migrator will still report success',
        );
      }
    }

    expect(outOfOrder).toEqual([]);
  });

  it('has no `when` in the future', () => {
    // A future timestamp poisons the watermark: every migration generated before that moment
    // arrives is skipped. This is exactly how 0010 was lost.
    const now = Date.now();
    const future = journal().entries.filter((e) => e.when > now);
    expect(future.map((e) => `${e.tag} is dated ${new Date(e.when).toISOString()}`)).toEqual([]);
  });

  it('has one journal entry per .sql file, and vice versa', () => {
    // A .sql file with no journal entry never runs (this happened to 0006, which sat orphaned on
    // disk for weeks). A journal entry with no file crashes the migrator at boot.
    const files = readdirSync(MIGRATIONS)
      .filter((f) => f.endsWith('.sql'))
      .map((f) => f.replace(/\.sql$/, ''))
      .sort();
    const tags = journal().entries.map((e) => e.tag).sort();

    expect(tags).toEqual(files);
  });

  it('numbers entries consecutively from zero', () => {
    const entries = journal().entries;
    expect(entries.map((e) => e.idx)).toEqual(entries.map((_, i) => i));
  });
});
