import { readFile } from 'node:fs/promises';
import { setTimeout as delay } from 'node:timers/promises';
import {
  AudioFrame,
  AudioSource,
  LocalAudioTrack,
  type Room,
  RoomEvent,
  TrackPublishOptions,
  TrackSource,
} from '@livekit/rtc-node';

/**
 * The recorded-call notice pre-roll — Israeli Wiretapping Law (1979) §2 says every party must be
 * told the call is recorded, and a compliance line we cannot PROVE played is worth nothing in a
 * dispute. So this is a static asset (assets/recording-notice.wav, generated by
 * scripts/generate-recording-notice.mjs, spoken by a flat broadcast voice that is deliberately
 * NOT Keren), played into the room as raw PCM before her greeting, and the outcome — played or
 * failed, with a timestamp — lands in call_learnings.analysis for every call.
 *
 * Product decision (2026-07-17): a robotic system announcement, then the human greeting. The
 * caller should hear the legal line as infrastructure, not as Keren being stiff. Bonus: the
 * ~2 seconds of playback are exactly when the pipeline warms up (DB flag read, provider
 * construction), so the notice costs the caller nothing.
 */

/** Where the asset lives, relative to the process CWD (repo root in dev, image root in deploy). */
export const RECORDING_NOTICE_PATH = 'assets/recording-notice.wav';

export interface ParsedWav {
  sampleRate: number;
  channels: number;
  pcm: Int16Array;
}

/**
 * Minimal RIFF/WAVE parser for OUR OWN asset — 16-bit PCM, the only thing the generator writes.
 * Throws on anything else rather than playing garbage into a caller's ear.
 */
export function parseWavPcm16(buf: Buffer): ParsedWav {
  if (buf.length < 44 || buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WAVE') {
    throw new Error('not a RIFF/WAVE file');
  }
  let offset = 12;
  let fmt: { channels: number; sampleRate: number; bitsPerSample: number } | null = null;
  while (offset + 8 <= buf.length) {
    const id = buf.toString('ascii', offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    const body = offset + 8;
    if (id === 'fmt ') {
      const format = buf.readUInt16LE(body);
      if (format !== 1) throw new Error(`unsupported WAV format ${format} — expected PCM`);
      fmt = {
        channels: buf.readUInt16LE(body + 2),
        sampleRate: buf.readUInt32LE(body + 4),
        bitsPerSample: buf.readUInt16LE(body + 14),
      };
      if (fmt.bitsPerSample !== 16) throw new Error(`unsupported bit depth ${fmt.bitsPerSample}`);
    } else if (id === 'data') {
      if (!fmt) throw new Error('WAV data chunk before fmt chunk');
      const bytes = Math.min(size, buf.length - body);
      // Int16Array over a Buffer slice needs 2-byte alignment — copy to be safe.
      const pcm = new Int16Array(bytes / 2);
      for (let i = 0; i < pcm.length; i++) pcm[i] = buf.readInt16LE(body + i * 2);
      return { sampleRate: fmt.sampleRate, channels: fmt.channels, pcm };
    }
    offset = body + size + (size % 2); // chunks are word-aligned
  }
  throw new Error('WAV has no data chunk');
}

/** 100ms per captured frame — the granularity LiveKit's jitter buffer is happiest with. */
const FRAME_MS = 100;

/**
 * How long to wait for the caller to actually SUBSCRIBE to the notice track before playing.
 *
 * WHY: the notice used to play the instant the track was published — but subscription negotiation
 * takes time, and a ~2s track that starts before anyone is attached is partly or fully missed.
 * Koren heard exactly that on 2026-07-20: log said played:true, his ears said nothing played.
 * `played:true` must mean "a subscribed listener existed while the audio went out", or it is a
 * compliance lie.
 */
const SUBSCRIBER_WAIT_MS = 5_000;

/** Jitter-buffer tail: audio still in flight when waitForPlayout resolves locally. Unpublishing
 * immediately clips the last words of the notice off the caller's ear. */
const TAIL_GRACE_MS = 500;

/** Resolves true when OUR publication gains a subscriber, false on timeout. */
function waitForSubscriber(room: Room, trackSid: string, timeoutMs: number): Promise<boolean> {
  return new Promise((resolve) => {
    let timer: ReturnType<typeof setTimeout> | undefined;
    const onSubscribed = (track: { sid?: string }): void => {
      if (track?.sid && track.sid !== trackSid) return; // someone else's track
      cleanup();
      resolve(true);
    };
    const cleanup = (): void => {
      if (timer) clearTimeout(timer);
      room.off(RoomEvent.LocalTrackSubscribed, onSubscribed);
    };
    room.on(RoomEvent.LocalTrackSubscribed, onSubscribed);
    timer = setTimeout(() => {
      cleanup();
      resolve(false);
    }, timeoutMs);
  });
}

/**
 * Plays the notice into the room and resolves when the audio has fully played out.
 * Returns the ISO timestamp of playback start on success, null on ANY failure — the caller logs
 * the outcome either way, because "we don't know if it played" must be visible, not silent.
 *
 * Failure policy (documented product decision): a failed notice is logged loudly but does NOT
 * abort the call. Revisit if counsel says otherwise.
 */
export async function playRecordingNotice(
  room: Room,
  assetPath: string = RECORDING_NOTICE_PATH,
): Promise<string | null> {
  let source: AudioSource | null = null;
  try {
    const { sampleRate, channels, pcm } = parseWavPcm16(await readFile(assetPath));
    if (channels !== 1) throw new Error(`expected mono asset, got ${channels} channels`);

    source = new AudioSource(sampleRate, 1);
    const track = LocalAudioTrack.createAudioTrack('recording-notice', source);
    const options = new TrackPublishOptions({ source: TrackSource.SOURCE_MICROPHONE });
    const publication = await room.localParticipant?.publishTrack(track, options);
    if (!publication) throw new Error('no local participant to publish from');

    // Do NOT play into an empty line: wait until the caller's client has actually subscribed.
    // On timeout we play anyway (a SIP participant may not surface the event) but say so in the
    // log — a notice nobody could hear must never be recorded as clean compliance silently.
    const subscribed = await waitForSubscriber(room, publication.sid ?? '', SUBSCRIBER_WAIT_MS);
    if (!subscribed) console.error('recording_notice_no_subscriber_confirmed');

    const startedAt = new Date().toISOString();
    const samplesPerFrame = Math.floor((sampleRate * FRAME_MS) / 1000);
    for (let off = 0; off < pcm.length; off += samplesPerFrame) {
      const chunk = pcm.subarray(off, Math.min(off + samplesPerFrame, pcm.length));
      await source.captureFrame(new AudioFrame(chunk, sampleRate, 1, chunk.length));
    }
    await source.waitForPlayout();
    // Let the network tail drain — unpublishing on the local playout edge clips the last words.
    await delay(TAIL_GRACE_MS);

    await room.localParticipant?.unpublishTrack(publication.sid!).catch(() => undefined);
    return startedAt;
  } catch (err) {
    console.error(
      'recording_notice_failed',
      err instanceof Error ? err.message : String(err),
    );
    return null;
  } finally {
    await source?.close().catch(() => undefined);
  }
}
